generate-website: Don't require generate-documentation to succeed
pandoc on RHEL 5 may be tedious to get going.

diff --git a/bin/generate-website b/bin/generate-website
--- a/bin/generate-website
+++ b/bin/generate-website
@@ -36,4 +36,6 @@ echo "Rendering template"
 $bin/fill-template --output=$output --find-exports=$exports $base/web/index.tt
 
 echo "Generating documentation"
-$bin/generate-documentation $output
+if ! $bin/generate-documentation $output; then
+    echo "Warning: Couldn't generate documentation, but proceeding anyway"
+fi
